# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20160325_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shisha',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
