# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20160326_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quickstart.Vendor'),
        ),
        migrations.AlterField(
            model_name='shisha',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quickstart.Manufacturer'),
        ),
    ]
