# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20160326_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shisha',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shisha',
            name='flavour',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
